import { ArrowRight, BarChart3, BookOpen, GraduationCap, Sparkles, Target } from "lucide-react";
import { Link } from "react-router-dom";
import MentionMaxLogo from "../assets/brand/mentionmax-logo.svg";
import "./Landing.css";

export default function Landing() {
  return <main style={{ minHeight: "100vh", background: "#F4FAF8", color: "#073B3A", fontFamily: "Inter, system-ui, sans-serif" }}>
    <nav style={{ height: 72, borderBottom: "1px solid #DDEBE8", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 7vw", background: "rgba(244,250,248,.92)", position: "sticky", top: 0, zIndex: 10 }}>
      <Link to="/" style={{ display: "flex", alignItems: "center" }}><img src={MentionMaxLogo} alt="MentionMax" style={{ width: 150, height: "auto" }} /></Link>
      <div style={{ display: "flex", gap: 28, alignItems: "center" }}><a href="#plateforme" style={{ color: "#54736F", textDecoration: "none", fontSize: 13 }}>Plateforme</a><a href="#parcours" style={{ color: "#54736F", textDecoration: "none", fontSize: 13 }}>Parcours</a><a href="#mission" style={{ color: "#54736F", textDecoration: "none", fontSize: 13 }}>Mission Helios</a><Link to="/connexion" style={{ color: "#073B3A", textDecoration: "none", fontWeight: 800, fontSize: 13 }}>Se connecter</Link><Link to="/connexion" style={{ background: "#0FA3A3", color: "white", textDecoration: "none", padding: "11px 16px", borderRadius: 10, fontWeight: 800, fontSize: 13, display: "inline-flex", gap: 7, alignItems: "center" }}>Commencer <ArrowRight size={15} /></Link></div>
    </nav>
    <section style={{ maxWidth: 1380, margin: "0 auto", padding: "86px 7vw 80px", display: "grid", gridTemplateColumns: "1.02fr .98fr", gap: 60, alignItems: "center" }}>
      <div><span style={{ color: "#0FA3A3", fontSize: 11, fontWeight: 900, letterSpacing: ".12em", textTransform: "uppercase", display: "inline-flex", gap: 7, alignItems: "center" }}><Sparkles size={14} /> Préparation 2BAC · Maroc</span><h1 style={{ fontSize: "clamp(48px,6vw,82px)", lineHeight: .98, letterSpacing: "-.055em", margin: "20px 0", maxWidth: 760 }}>Travaille le cours.<br /><span style={{ color: "#0FA3A3" }}>Maîtrise le Bac.</span></h1><p style={{ maxWidth: 650, fontSize: 18, lineHeight: 1.65, color: "#587570", margin: 0 }}>Une plateforme pensée pour le 2BAC : cours, exercices, IA et annales réunis autour d’un seul objectif, progresser réellement.</p><div style={{ display: "flex", gap: 12, marginTop: 30, flexWrap: "wrap" }}><Link to="/connexion" style={{ background: "#0FA3A3", color: "white", textDecoration: "none", padding: "13px 18px", borderRadius: 11, fontWeight: 900, fontSize: 14, display: "inline-flex", gap: 8, alignItems: "center" }}>Commencer gratuitement <ArrowRight size={16} /></Link><a href="#plateforme" style={{ border: "1px solid #CFE2DF", color: "#073B3A", textDecoration: "none", padding: "12px 18px", borderRadius: 11, fontWeight: 800, fontSize: 14 }}>Découvrir la plateforme</a></div><div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginTop: 22 }}><span style={{ background: "white", border: "1px solid #DDEBE8", borderRadius: 99, padding: "7px 10px", fontSize: 11, fontWeight: 800 }}>2BAC</span><span style={{ background: "white", border: "1px solid #DDEBE8", borderRadius: 99, padding: "7px 10px", fontSize: 11, fontWeight: 800 }}>3 parcours</span><span style={{ background: "white", border: "1px solid #DDEBE8", borderRadius: 99, padding: "7px 10px", fontSize: 11, fontWeight: 800 }}>5 matières</span><span style={{ background: "white", border: "1px solid #DDEBE8", borderRadius: 99, padding: "7px 10px", fontSize: 11, fontWeight: 800 }}>300 exercices Helios</span></div></div>
      <div style={{ background: "#E1F4F0", border: "1px solid #D0EAE6", borderRadius: 28, padding: 20, boxShadow: "0 28px 70px rgba(7,59,58,.1)" }}><div style={{ background: "white", border: "1px solid #DDEBE8", borderRadius: 19, padding: 20 }}><div style={{ display: "flex", justifyContent: "space-between", color: "#0FA3A3", fontSize: 10, fontWeight: 900, letterSpacing: ".1em" }}><span>MENTIONMAX</span><span>2BAC · SM A</span></div><div style={{ margin: "26px 0 16px" }}><small style={{ color: "#91A5A1", fontSize: 9, fontWeight: 900, letterSpacing: ".1em" }}>AUJOURD’HUI</small><h2 style={{ margin: "6px 0 0", fontSize: 25 }}>Continue ton travail</h2></div>{[["01","Limites et continuité","Mathématiques · 20 min","Commencer"],["02","Mécanique","Physique-Chimie · Révision","Voir"],["03","Assistant IA","Une question en attente","Ouvrir"]].map(([n,t,s,a],i)=><div key={n} style={{ display: "grid", gridTemplateColumns: "34px 1fr auto", gap: 11, alignItems: "center", padding: "14px 0", borderTop: "1px solid #EDF2F1" }}><span style={{ width: 30, height: 30, borderRadius: 9, display: "grid", placeItems: "center", background: i===0?"#DDF5F1":"#F0F5F4", color: "#0FA3A3", fontSize: 10, fontWeight: 900 }}>{n}</span><div><strong style={{ display: "block", fontSize: 12 }}>{t}</strong><small style={{ color: "#7C9290", fontSize: 10 }}>{s}</small></div><b style={{ fontSize: 9, color: i===0?"#0FA3A3":"#849A96" }}>{a}</b></div>)}<div style={{ marginTop: 22, borderTop: "1px solid #EDF2F1", paddingTop: 16 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "#778D89", fontWeight: 800 }}><span>Progression hebdo</span><strong style={{ color: "#073B3A" }}>68%</strong></div><div style={{ height: 7, background: "#E7EFED", borderRadius: 99, overflow: "hidden", marginTop: 8 }}><div style={{ width: "68%", height: "100%", background: "#0FA3A3", borderRadius: 99 }} /></div></div></div></div>
    </section>
    <section id="plateforme" style={{ background: "white", borderTop: "1px solid #DDEBE8", borderBottom: "1px solid #DDEBE8", padding: "90px 7vw" }}><div style={{ maxWidth: 1380, margin: "0 auto" }}><span style={{ color: "#0FA3A3", fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>LA LOGIQUE</span><h2 style={{ fontSize: "clamp(34px,4vw,54px)", letterSpacing: "-.04em", margin: "12px 0" }}>Comprendre. Pratiquer. Mesurer.</h2><p style={{ maxWidth: 700, color: "#66807C", lineHeight: 1.65 }}>Chaque partie de MentionMax a une fonction claire dans ton parcours de révision.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 16, marginTop: 38 }}>{[[BookOpen,"Cours","Des leçons structurées autour du programme 2BAC."],[Target,"Pratique","Des exercices pour transformer le cours en réflexes."],[BarChart3,"Progression","Un suivi lisible pour savoir quoi retravailler."]].map(([Icon,title,text])=><article key={title as string} style={{ padding: 25, border: "1px solid #DDEBE8", borderRadius: 18, background: "#FBFDFC" }}><div style={{ width: 40, height: 40, borderRadius: 11, background: "#DDF5F1", color: "#0FA3A3", display: "grid", placeItems: "center" }}><Icon size={18} /></div><h3 style={{ fontSize: 19, margin: "18px 0 7px" }}>{title as string}</h3><p style={{ margin: 0, color: "#6B8581", lineHeight: 1.55, fontSize: 13 }}>{text as string}</p></article>)}</div></div></section>
    <section id="parcours" style={{ padding: "90px 7vw", maxWidth: 1380, margin: "0 auto" }}><span style={{ color: "#0FA3A3", fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>PARCOURS</span><h2 style={{ fontSize: "clamp(34px,4vw,54px)", letterSpacing: "-.04em", margin: "12px 0" }}>Ton contenu suit ta série.</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 16, marginTop: 32 }}>{[["SPC","Sciences Physiques","Maths · PC · SVT · Philo · Anglais"],["SM A","Sciences Mathématiques A","Maths · PC · Philo · Anglais"],["SM B","Sciences Mathématiques B","Maths · PC · Philo · Anglais"]].map(([code,title,subjects])=><article key={code} style={{ background: "white", border: "1px solid #DDEBE8", borderRadius: 18, padding: 24 }}><strong style={{ color: "#0FA3A3", fontSize: 13 }}>{code}</strong><h3 style={{ margin: "20px 0 8px", fontSize: 20 }}>{title}</h3><p style={{ minHeight: 42, margin: 0, color: "#6B8581", lineHeight: 1.5, fontSize: 13 }}>{subjects}</p><Link to="/connexion" style={{ marginTop: 20, color: "#073B3A", textDecoration: "none", fontSize: 12, fontWeight: 900, display: "inline-flex", alignItems: "center", gap: 6 }}>Commencer ce parcours <ArrowRight size={13} /></Link></article>)}</div></section>
    <section id="mission" style={{ padding: "0 7vw 90px", maxWidth: 1380, margin: "0 auto" }}><div style={{ borderRadius: 25, background: "#073B3A", color: "white", padding: 34, display: "grid", gridTemplateColumns: "1fr .8fr", gap: 30, alignItems: "center" }}><div><span style={{ color: "#76DAD3", fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>MISSION HELIOS</span><h2 style={{ fontSize: "clamp(34px,4vw,54px)", letterSpacing: "-.04em", margin: "12px 0" }}>300 exercices.<br />15 jours.</h2><p style={{ color: "#B4D1CE", lineHeight: 1.6, maxWidth: 620 }}>Une progression complète en mathématiques, avec 20 exercices par chapitre et une difficulté qui augmente au fil de la mission.</p><Link to="/connexion" style={{ marginTop: 12, display: "inline-flex", gap: 8, alignItems: "center", background: "white", color: "#073B3A", padding: "12px 16px", borderRadius: 10, textDecoration: "none", fontWeight: 900, fontSize: 12 }}>Entrer dans Helios <ArrowRight size={15} /></Link></div><div style={{ background: "rgba(255,255,255,.06)", border: "1px solid rgba(255,255,255,.1)", borderRadius: 18, padding: 20 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 9, fontWeight: 900, letterSpacing: ".1em", color: "#8FB9B4" }}><span>MISSION HELIOS</span><span>JOUR 08 / 15</span></div><h3 style={{ fontSize: 23, margin: "20px 0 5px" }}>Calcul intégral</h3><p style={{ color: "#A9C7C3", fontSize: 11 }}>10 / 20 exercices terminés</p><div style={{ height: 8, background: "rgba(255,255,255,.1)", borderRadius: 99, overflow: "hidden", marginTop: 20 }}><div style={{ width: "50%", height: "100%", background: "#4FCFC8" }} /></div>{["Intégrale simple","Théorème fondamental","Aire entre courbes","Valeur moyenne"].map((x,i)=><div key={x} style={{ display: "flex", justifyContent: "space-between", borderTop: "1px solid rgba(255,255,255,.08)", padding: "11px 0", marginTop: i===0?18:0, fontSize: 11 }}><span style={{ color: i<2?"#D9EFEC":"#A7C5C1" }}>{i<2?"✓":"○"} {x}</span><b style={{ color: "#88BDB8" }}>{8+i}</b></div>)}</div></div></section>
    <section style={{ padding: "72px 7vw", borderTop: "1px solid #DDEBE8", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 30, maxWidth: 1380, margin: "0 auto" }}><div><span style={{ color: "#0FA3A3", fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>MENTIONMAX</span><h2 style={{ fontSize: 36, letterSpacing: "-.04em", margin: "10px 0 0" }}>Commence par un chapitre.<br />Construis la suite.</h2></div><Link to="/connexion" style={{ display: "inline-flex", gap: 8, alignItems: "center", background: "#0FA3A3", color: "white", padding: "13px 18px", borderRadius: 11, textDecoration: "none", fontWeight: 900, fontSize: 13 }}>Ouvrir MentionMax <ArrowRight size={16} /></Link></section>
    <footer style={{ borderTop: "1px solid #DDEBE8", padding: "25px 7vw", display: "flex", justifyContent: "space-between", gap: 20, color: "#7A9290", fontSize: 11 }}><img src={MentionMaxLogo} alt="MentionMax" style={{ width: 120 }} /><span>Préparation au Bac marocain · 2BAC</span><span>Comprendre le cours avant de compter les points.</span></footer>
  </main>;
}
