import type { LessonDocument } from "../../types/academic";

type Seed = [string, string, string, string, string, string, string, string, string, string[]];

const seeds: Seed[] = [
  ["lesson-maths-logique", "Logique mathématique", "Logique et raisonnement", "Propositions, quantificateurs et démonstrations.", "Une proposition possède une valeur de vérité. Les connecteurs et quantificateurs permettent de construire et lire des énoncés complexes.", "\\forall x\\in E,\\;P(x)", "\\exists x\\in E,\\;P(x)", "Identifier les hypothèses, choisir le raisonnement adapté, justifier chaque étape puis conclure.", "Une implication A\\Rightarrow B ne donne pas automatiquement B\\Rightarrow A.", ["Identifier proposition et connecteurs", "Utiliser les quantificateurs", "Choisir un raisonnement", "Conclure"]],
  ["lesson-maths-ensembles", "Ensembles et applications", "Ensembles et applications", "Manipuler les opérations sur les ensembles et les propriétés des applications.", "Union, intersection et complémentaire permettent de décrire des ensembles. Une application associe à chaque élément du domaine une image unique.", "A\\subset B\\Longleftrightarrow\\forall x,\\;x\\in A\\Rightarrow x\\in B", "(g\\circ f)(x)=g(f(x))", "Pour l'injectivité, partir de f(x)=f(y). Pour la surjectivité, partir d'un élément cible et chercher un antécédent.", "Ne pas confondre image directe et image réciproque.", ["Manipuler union et intersection", "Distinguer injection, surjection et bijection", "Calculer image et image réciproque"]],
  ["lesson-maths-fonctions", "Généralités sur les fonctions numériques", "Fonctions numériques", "Déterminer domaine, parité, variations, compositions et transformations graphiques.", "L'étude d'une fonction commence par son domaine, puis ses symétries, valeurs remarquables et variations.", "(g\\circ f)(x)=g(f(x))", "f(-x)=f(x)\\Rightarrow f\\text{ paire}", "Déterminer d'abord où l'expression est définie, puis étudier les propriétés demandées dans un ordre stable.", "Une symétrie graphique doit être identifiée précisément avant de conclure qu'une fonction est paire ou impaire.", ["Déterminer le domaine", "Étudier parité et variations", "Maîtriser composition et transformations"]],
  ["lesson-maths-barycentre", "Le barycentre dans le plan", "Géométrie affine", "Utiliser le barycentre pour traduire une configuration géométrique en relation vectorielle.", "Le barycentre condense une combinaison affine de points pondérés en un point unique.", "\\vec{OG}=\\frac{a\\vec{OA}+b\\vec{OB}}{a+b}", "a\\vec{GA}+b\\vec{GB}=\\vec0", "Choisir une origine, écrire les vecteurs de position et simplifier la combinaison pondérée.", "La somme des coefficients doit être non nulle pour utiliser la formule à deux points.", ["Écrire la relation barycentrique", "Vérifier les coefficients", "Exploiter l'associativité"]],
  ["lesson-maths-produit-scalaire-plan", "Produit scalaire dans le plan", "Produit scalaire", "Relier calcul analytique, normes, angles et orthogonalité.", "Le produit scalaire permet de calculer des angles, des longueurs et de tester l'orthogonalité.", "\\vec u\\cdot\\vec v=\\|\\vec u\\|\\|\\vec v\\|\\cos(\\theta)", "\\vec u\\perp\\vec v\\Longleftrightarrow\\vec u\\cdot\\vec v=0", "Choisir la formule la plus directe : coordonnées pour un calcul rapide, norme-angle ou projection pour une interprétation géométrique.", "Un produit scalaire nul caractérise l'orthogonalité, pas la colinéarité.", ["Calculer un produit scalaire", "Tester l'orthogonalité", "Relier produit scalaire, norme et angle"]],
  ["lesson-maths-trig", "Calcul trigonométrique", "Trigonométrie", "Transformer des expressions et résoudre des équations trigonométriques.", "Les identités trigonométriques permettent de réduire, factoriser et transformer des expressions avant de résoudre.", "\\cos^2x+\\sin^2x=1", "\\cos(a+b)=\\cos a\\cos b-\\sin a\\sin b", "Transformer l'expression, factoriser si possible, puis résoudre sur l'intervalle demandé en tenant compte de la périodicité.", "Mélanger degrés et radians ou oublier les familles de solutions.", ["Transformer une expression", "Utiliser les identités", "Résoudre sur un intervalle"]],
  ["lesson-maths-suites", "Les suites numériques", "Suites", "Étudier les suites arithmétiques, géométriques et récurrentes.", "Une suite peut être explicite ou récurrente. Les suites arithmétiques et géométriques disposent de formules générales simples.", "u_n=u_0+nr", "v_n=v_0q^n", "Identifier la nature, écrire le terme général, puis étudier variation, bornes ou somme selon la question.", "Ne pas appliquer une formule arithmétique à une suite géométrique, ou inversement.", ["Identifier la nature de la suite", "Écrire le terme général", "Étudier variation et somme"]],
  ["lesson-maths-rotation", "La rotation dans le plan", "Transformations", "Décrire une rotation par son centre et son angle et exploiter ses invariants.", "Une rotation conserve distances et angles. En complexes, une rotation centrée en l'origine est une multiplication par un nombre de module 1.", "z'=e^{i\\theta}z", "AM'=AM", "Identifier centre et angle, puis choisir la représentation géométrique ou complexe adaptée.", "Une rotation conserve les longueurs, contrairement à une homothétie de rapport différent de 1.", ["Identifier centre et angle", "Utiliser les invariants", "Vérifier l'image de points"]],
  ["lesson-maths-limites", "Les limites d'une fonction numérique", "Limites", "Calculer des limites et interpréter le comportement d'une fonction.", "Une limite décrit le comportement de f(x) lorsque x approche une valeur ou devient très grand.", "\\lim_{x\\to a}f(x)=L", "\\lim_{x\\to\\infty}\\frac1x=0", "Commencer par une substitution directe. Si nécessaire, factoriser, rationaliser ou comparer les termes dominants.", "Une limite infinie décrit un comportement, pas une valeur prise par la fonction.", ["Identifier la forme de limite", "Transformer l'expression", "Conclure sur le comportement"]],
  ["lesson-maths-derivation", "La dérivation d'une fonction numérique", "Dérivation", "Calculer un nombre dérivé et exploiter la dérivée.", "La dérivée mesure la variation locale et fournit le coefficient directeur de la tangente.", "f'(a)=\\lim_{h\\to0}\\frac{f(a+h)-f(a)}h", "y=f(a)+f'(a)(x-a)", "Dériver, résoudre f'(x)=0, étudier le signe de f' puis déduire les variations.", "Confondre f(a) et f'(a).", ["Dériver", "Étudier le signe de la dérivée", "Construire les variations"]],
  ["lesson-maths-etude-fonctions", "Étude et représentation d'une fonction", "Étude complète", "Construire une étude complète jusqu'au tracé cohérent.", "Une étude rassemble domaine, limites, dérivée, variations, extrema, asymptotes et points utiles au graphique.", "f'(x)>0\\Rightarrow f\\text{ croissante}", "\\lim_{x\\to\\infty}f(x)=\\pm\\infty", "Suivre un ordre stable : domaine, limites, dérivée, signe, variations, intersections, asymptotes puis tracé.", "Tracer une courbe sans avoir justifié les informations qui la déterminent.", ["Domaine et limites", "Dérivée et signe", "Variations, asymptotes et tracé"]],
  ["lesson-maths-vecteurs-espace", "Vecteurs de l'espace", "Géométrie de l'espace", "Manipuler coordonnées, colinéarité et coplanarité dans l'espace.", "Un vecteur de l'espace possède trois coordonnées. Les propriétés se traduisent par des relations linéaires entre vecteurs.", "\\vec u=(x,y,z)", "\\vec u\\parallel\\vec v\\Longleftrightarrow\\exists k,\\;\\vec u=k\\vec v", "Calculer les coordonnées puis rechercher un coefficient commun ou une relation linéaire selon la propriété demandée.", "Vérifier seulement deux coordonnées peut conduire à une fausse conclusion en 3D.", ["Calculer les coordonnées", "Tester colinéarité et coplanarité", "Interpréter dans l'espace"]],
  ["lesson-maths-geometrie-espace", "Géométrie analytique de l'espace", "Droites et plans", "Écrire des équations de droites et de plans.", "Un plan se décrit avec un vecteur normal et une équation cartésienne ; une droite avec un point et un vecteur directeur.", "ax+by+cz+d=0", "(x,y,z)=A+t\\vec u", "Identifier les données géométriques, construire l'équation puis tester appartenance ou position relative.", "Confondre vecteur directeur d'une droite et vecteur normal d'un plan.", ["Construire droite ou plan", "Étudier les positions relatives", "Vérifier appartenance et distances"]],
  ["lesson-maths-denombrement", "Dénombrement", "Combinatoire", "Compter des configurations sans double comptage.", "Le bon outil dépend de l'ordre, de la répétition et du nombre d'éléments choisis.", "\\binom nk=\\frac{n!}{k!(n-k)!}", "A_n^k=\\frac{n!}{(n-k)!}", "Se demander d'abord si l'ordre compte et si les répétitions sont autorisées, puis choisir la formule.", "Compter deux fois une même configuration ou choisir une combinaison lorsque l'ordre intervient.", ["Identifier si l'ordre compte", "Choisir la bonne formule", "Vérifier le comptage"]],
  ["lesson-maths-scalaire-espace", "Produit scalaire dans l'espace", "Produit scalaire 3D", "Étendre le produit scalaire aux vecteurs de l'espace.", "Le produit scalaire sert notamment à caractériser l'orthogonalité et à construire des conditions de plans.", "\\vec u\\cdot\\vec v=xx'+yy'+zz'", "\\|\\vec u\\|^2=\\vec u\\cdot\\vec u", "Utiliser directement les coordonnées pour les calculs et interpréter ensuite le résultat géométriquement.", "Oublier le troisième terme du calcul en trois dimensions.", ["Calculer en coordonnées", "Tester orthogonalité", "Interpréter le résultat"]],
  ["lesson-maths-arithmetique", "Arithmétique dans Z", "Divisibilité et congruences", "Utiliser division euclidienne, PGCD, Bézout et congruences.", "Les congruences simplifient les problèmes de divisibilité et les relations entre entiers modulo un nombre.", "a=bq+r,\\quad0\\le r<b", "au+bv=\\gcd(a,b)", "Choisir l'outil adapté, réduire les nombres modulo n lorsque pertinent, puis justifier chaque transformation.", "Diviser modulo n sans vérifier que le facteur possède un inverse modulo n.", ["Choisir division, PGCD ou congruence", "Réduire modulo n", "Justifier la conclusion"]],
  ["lesson-maths-vectoriel", "Produit vectoriel", "Produit vectoriel", "Calculer un produit vectoriel et l'utiliser en géométrie.", "Le produit vectoriel est orthogonal aux deux vecteurs et sa norme donne l'aire du parallélogramme associé.", "\\vec u\\times\\vec v=(yz'-zy',zx'-xz',xy'-yx')", "\\|\\vec u\\times\\vec v\\|=\\|\\vec u\\|\\|\\vec v\\|\\sin\\theta", "Calculer les coordonnées, vérifier l'orthogonalité puis exploiter la norme pour une aire ou un volume.", "Inverser l'ordre change le signe : u×v = −(v×u).", ["Calculer le produit vectoriel", "Vérifier l'orthogonalité", "Utiliser la norme pour les aires"]],
];

function makeLesson(seed: Seed): LessonDocument {
  const [id, title, chapter, intro, concept, formula1, formula2, method, mistake, recap] = seed;
  return {
    id, title, language: "fr", source: "APPROVED", subjectId: "maths", chapter, topic: title,
    blocks: [
      { type: "title", title },
      { type: "intro", text: intro },
      { type: "concept", title: "L'idée essentielle", text: concept },
      { type: "formula", latex: formula1 },
      { type: "formula", latex: formula2 },
      { type: "method", title: "Méthode", text: method },
      { type: "common-mistake", title: "Erreur fréquente", text: mistake },
      { type: "exam-tip", title: "Réflexe Bac", text: "Rédiger la conclusion avec le vocabulaire exact du cours et vérifier chaque hypothèse utilisée." },
      { type: "recap", title: "À retenir", items: recap },
    ],
  };
}

export const mathLessons = seeds.map(makeLesson);
