import type { LessonDocument } from "../../types/academic";

const lessons: LessonDocument[] = [
  {
    id: "lesson-pc-travail-puissance",
    title: "Travail et puissance d'une force",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Travail et puissance",
    topic: "Travail et puissance d'une force",
    blocks: [
      { type: "title", title: "Travail et puissance d'une force" },
      { type: "intro", text: "Évaluer l'effet mécanique d'une force sur un déplacement et relier travail et puissance." },
      { type: "concept", title: "Idée essentielle", text: "Le travail traduit l'énergie transférée par une force lors d'un déplacement. Pour une force constante, il dépend de la force, du déplacement et de l'angle entre eux." },
      { type: "formula", latex: "W_{AB}(\\vec F)=F\\,AB\\cos(\\alpha)" },
      { type: "formula", latex: "P=\\frac{W}{\\Delta t}" },
      { type: "method", title: "Méthode", text: "Identifier la force, le déplacement et l'angle. Déterminer le signe du travail puis calculer la puissance moyenne si une durée est donnée." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Oublier que le travail peut être positif, nul ou négatif selon l'orientation de la force." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Toujours préciser l'unité : joule pour un travail, watt pour une puissance." },
      { type: "recap", title: "À retenir", items: ["Travail d'une force", "Signe selon l'angle", "Puissance = travail par unité de temps"] },
    ],
  },
  {
    id: "lesson-pc-energie-cinetique",
    title: "Énergie cinétique et théorème",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Énergie cinétique",
    topic: "Théorème de l'énergie cinétique",
    blocks: [
      { type: "title", title: "Énergie cinétique et théorème" },
      { type: "intro", text: "Relier la variation de vitesse d'un système au travail des forces qui lui sont appliquées." },
      { type: "definition", title: "Énergie cinétique", text: "L'énergie cinétique dépend de la masse du système et du carré de sa vitesse." },
      { type: "formula", latex: "E_c=\\frac12mv^2" },
      { type: "theorem", title: "Théorème", text: "La variation d'énergie cinétique entre deux positions est égale à la somme des travaux des forces extérieures." },
      { type: "formula", latex: "\\Delta E_c=\\sum W(\\vec F)" },
      { type: "method", title: "Méthode", text: "Faire l'inventaire des forces, calculer leurs travaux puis utiliser le théorème pour relier le résultat à la vitesse." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Utiliser v au lieu de v² dans l'énergie cinétique." },
      { type: "recap", title: "À retenir", items: ["E_c=½mv²", "Variation d'énergie cinétique", "Somme des travaux"] },
    ],
  },
  {
    id: "lesson-pc-champ-electrostatique",
    title: "Champ électrostatique",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Champ électrostatique",
    topic: "Champ créé par une charge",
    blocks: [
      { type: "title", title: "Champ électrostatique" },
      { type: "intro", text: "Comprendre l'action à distance d'une charge électrique et calculer le champ en un point." },
      { type: "concept", title: "Idée essentielle", text: "Une charge électrique crée un champ dans l'espace. Une charge test placée dans ce champ subit une force proportionnelle au champ." },
      { type: "formula", latex: "\\vec F=q\\vec E" },
      { type: "formula", latex: "E=\\frac{k|Q|}{r^2}" },
      { type: "method", title: "Méthode", text: "Repérer le signe de la charge source, déterminer la direction du champ, puis appliquer la loi de Coulomb ou la relation F=qE." },
      { type: "warning", title: "Attention", text: "Le champ est orienté selon le signe de la charge source ; la force dépend ensuite du signe de la charge placée dans le champ." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Faire un schéma des directions avant le calcul vectoriel." },
      { type: "recap", title: "À retenir", items: ["F=qE", "E=k|Q|/r²", "Direction et signe comptent"] },
    ],
  },
  {
    id: "lesson-pc-quantite-matiere",
    title: "Quantité de matière et concentration",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Quantité de matière",
    topic: "Solutions et concentrations",
    blocks: [
      { type: "title", title: "Quantité de matière et concentration" },
      { type: "intro", text: "Passer entre masse, quantité de matière, concentration et volume dans les solutions." },
      { type: "formula", latex: "n=\\frac{m}{M}" },
      { type: "formula", latex: "C=\\frac{n}{V}" },
      { type: "method", title: "Méthode", text: "Convertir les données dans des unités cohérentes, calculer n si nécessaire, puis utiliser la relation de concentration avec le volume de solution." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Confondre concentration molaire et masse molaire, ou laisser un volume en mL sans conversion lorsqu'une unité SI est requise." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Vérifier systématiquement les unités avant le remplacement numérique." },
      { type: "recap", title: "À retenir", items: ["n=m/M", "C=n/V", "Conversions avant calcul"] },
    ],
  },
  {
    id: "lesson-pc-dilution",
    title: "Préparation et dilution d'une solution",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Solutions aqueuses",
    topic: "Dilution",
    blocks: [
      { type: "title", title: "Préparation et dilution d'une solution" },
      { type: "intro", text: "Préparer une solution fille à partir d'une solution mère en conservant la quantité de soluté prélevée." },
      { type: "formula", latex: "C_mV_m=C_fV_f" },
      { type: "method", title: "Méthode", text: "Identifier les concentrations mère et fille ainsi que les volumes, isoler l'inconnue puis choisir le volume à prélever avec une pipette adaptée." },
      { type: "example", title: "Exemple", text: "Pour préparer 100 mL d'une solution à 0,20 mol·L⁻¹ depuis une solution mère à 1,0 mol·L⁻¹, le volume mère nécessaire est 20 mL." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Inverser concentration mère et fille : une dilution donne toujours une solution fille moins concentrée." },
      { type: "recap", title: "À retenir", items: ["La quantité de soluté se conserve", "C_mV_m=C_fV_f", "C_f<C_m"] },
    ],
  },
  {
    id: "lesson-pc-reactions-acido-basiques",
    title: "Réactions acido-basiques",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Réactions acido-basiques",
    topic: "pH et couples acide-base",
    blocks: [
      { type: "title", title: "Réactions acido-basiques" },
      { type: "intro", text: "Identifier les couples acide/base, écrire une réaction et relier pH et concentration en ions oxonium." },
      { type: "definition", title: "Couple", text: "Deux espèces forment un couple acide/base lorsqu'elles ne diffèrent que par un proton H⁺." },
      { type: "formula", latex: "pH=-\\log[H_3O^+]" },
      { type: "method", title: "Méthode", text: "Identifier donneur et accepteur de proton, écrire les deux demi-équations puis les combiner pour obtenir la réaction globale." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Écrire une réaction acido-basique sans respecter la conservation des atomes et des charges." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Vérifier séparément conservation des éléments et de la charge électrique." },
      { type: "recap", title: "À retenir", items: ["Identifier les couples", "Écrire les échanges de H⁺", "Relier pH et [H₃O⁺]"] },
    ],
  },
  {
    id: "lesson-pc-dosage",
    title: "Dosage par titrage",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Dosage",
    topic: "Équivalence",
    blocks: [
      { type: "title", title: "Dosage par titrage" },
      { type: "intro", text: "Déterminer une concentration inconnue à partir d'une réaction chimique connue et de l'équivalence." },
      { type: "concept", title: "Équivalence", text: "À l'équivalence, les réactifs introduits sont dans les proportions stœchiométriques de la réaction support du dosage." },
      { type: "formula", latex: "a\\,n_A=b\\,n_B" },
      { type: "method", title: "Méthode", text: "Écrire l'équation, repérer le volume à l'équivalence, appliquer les proportions stœchiométriques puis isoler la concentration recherchée." },
      { type: "warning", title: "Attention", text: "Le volume utilisé dans la relation d'équivalence est celui versé à l'équivalence, pas le volume ajouté à un instant quelconque." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Toujours écrire l'équation chimique avant d'établir la relation d'équivalence." },
      { type: "recap", title: "À retenir", items: ["Réaction support", "Volume équivalent", "Proportions stœchiométriques"] },
    ],
  },
  {
    id: "lesson-pc-oxydoreduction",
    title: "Oxydoréduction",
    language: "fr",
    source: "APPROVED",
    subjectId: "physique-chimie",
    chapter: "Oxydoréduction",
    topic: "Échange d'électrons",
    blocks: [
      { type: "title", title: "Oxydoréduction" },
      { type: "intro", text: "Reconnaître oxydant et réducteur, écrire les demi-équations puis équilibrer une réaction d'oxydoréduction." },
      { type: "definition", title: "Oxydant et réducteur", text: "Un oxydant capte des électrons ; un réducteur cède des électrons." },
      { type: "formula", latex: "Ox+ne^-\\rightleftharpoons Red" },
      { type: "method", title: "Méthode", text: "Écrire chaque demi-équation, équilibrer atomes et charges, puis multiplier pour avoir le même nombre d'électrons échangés avant d'additionner." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Inverser oxydation et réduction, ou oublier d'équilibrer les charges." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Vérifier les électrons perdus = électrons gagnés dans la réaction globale." },
      { type: "recap", title: "À retenir", items: ["Oxydant capte", "Réducteur cède", "Égalité des électrons échangés"] },
    ],
  },
];

export const pcLessons = lessons;
