import type { LessonDocument } from "../../types/academic";

const pcLesson = (
  id: string,
  title: string,
  chapter: string,
  topic: string,
  intro: string,
  blocks: LessonDocument["blocks"],
): LessonDocument => ({
  id,
  title,
  language: "fr",
  source: "APPROVED",
  subjectId: "physique-chimie",
  chapter,
  topic,
  blocks: [
    { type: "title", title },
    { type: "intro", text: intro },
    ...blocks,
  ],
});

export const secondBacPcLessonsDetailed: LessonDocument[] = [
  pcLesson(
    "2bac-pc-waves",
    "Ondes mécaniques progressives",
    "Ondes mécaniques progressives",
    "Célérité, retard et propagation",
    "Une onde mécanique progressive transmet une perturbation de proche en proche. Le milieu oscille localement, mais il n'y a pas de transport global de matière avec l'onde.",
    [
      { type: "definition", title: "Définition", text: "Une onde mécanique progressive est la propagation d'une perturbation dans un milieu matériel, sans transport global de matière." },
      { type: "concept", title: "L'idée à visualiser", text: "Imagine une déformation qui avance le long d'une corde : chaque point transmet la perturbation au suivant. La forme avance, les morceaux de corde restent autour de leur position d'équilibre." },
      { type: "formula", latex: "v=\\frac{d}{\\Delta t}" },
      { type: "example", title: "Exemple guidé", text: "Une perturbation parcourt 3,6 m sur une corde en 0,90 s. La célérité vaut v=3,6/0,90=4,0 m·s⁻¹." },
      { type: "worked-solution", title: "Lecture Bac", text: "On repère la distance entre les deux points, on identifie le retard de propagation, puis on applique v=d/Δt avec les unités cohérentes." },
      { type: "method", title: "Méthode Bac", text: "1. Identifier les deux points étudiés. 2. Relever la distance d. 3. Déterminer le retard Δt. 4. Écrire la relation littérale avant l'application numérique. 5. Contrôler l'unité de v." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Confondre célérité v, fréquence f et période T. Une onde peut avoir une même célérité et une fréquence différente selon la source." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Toujours écrire « la perturbation se propage » plutôt que « la matière se déplace avec l'onde »." },
      { type: "highlight", title: "Quick check", text: "Un signal met 5,0 ms pour parcourir 1,7 m. Estime sa célérité : environ 340 m·s⁻¹." },
      { type: "exercise", title: "Variante A", text: "Une impulsion parcourt 2,4 m en 7,0 ms. Calculer v puis rédiger une conclusion avec unité." },
      { type: "exercise", title: "Variante B", text: "Deux microphones sont séparés de 1,2 m et détectent un signal avec un retard de 3,5 ms. Déterminer la célérité." },
      { type: "diagram", title: "Visuel Menti", text: "Schéma horizontal d'une corde avec une impulsion en déplacement, deux points A et B, distance d et retard Δt annotés." },
      { type: "animation", title: "Animation", text: "Une impulsion se déplace le long d'une corde ; des repères montrent que chaque point oscille autour de sa position sans être transporté avec l'onde." },
    ],
  ),
  pcLesson(
    "2bac-pc-periodic",
    "Ondes mécaniques progressives périodiques",
    "Ondes mécaniques progressives périodiques",
    "Période, fréquence, longueur d'onde et phase",
    "Une onde périodique répète le même motif dans le temps et dans l'espace. Trois grandeurs se répondent : la période T, la fréquence f et la longueur d'onde λ.",
    [
      { type: "definition", title: "Double périodicité", text: "Une onde périodique présente une répétition temporelle de période T et une répétition spatiale de longueur d'onde λ." },
      { type: "formula", latex: "f=\\frac1T\\qquad ;\\qquad v=\\frac{\\lambda}{T}=\\lambda f" },
      { type: "formula", latex: "d=k\\lambda\\;\\text{pour des points en phase}" },
      { type: "concept", title: "À imaginer", text: "Si tu photographies la même onde à différents instants, tu observes le même motif décalé. La longueur d'onde mesure le déplacement du motif pendant une période." },
      { type: "example", title: "Exemple guidé", text: "Une onde a une fréquence de 25 Hz et une célérité de 5,0 m·s⁻¹. Alors λ=v/f=5,0/25=0,20 m." },
      { type: "method", title: "Méthode Bac", text: "1. Convertir la période en seconde si nécessaire. 2. Calculer f=1/T. 3. Choisir v=λ/T ou v=λf. 4. Vérifier que λ est en mètres si v est en m·s⁻¹." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Utiliser une période en millisecondes directement dans une formule en unités SI." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Quand un graphe est donné, lis d'abord l'échelle avant de calculer T ou λ. Beaucoup d'erreurs viennent du quadrillage, pas de la physique." },
      { type: "highlight", title: "Quick check", text: "Pour T=40 ms, la fréquence vaut 25 Hz." },
      { type: "exercise", title: "Variante A", text: "Une onde de fréquence 20 Hz se propage à 6,0 m·s⁻¹. Calculer λ." },
      { type: "exercise", title: "Variante B", text: "Deux points séparés de 45 cm sont en phase. Donner une relation possible entre leur distance et λ." },
      { type: "diagram", title: "Visuel Menti", text: "Deux vues de la même onde : graphe temporel pour T et instantané spatial pour λ, avec les mêmes crêtes mises en évidence." },
      { type: "interactive", title: "Interactif", text: "Curseurs T et v : calcul automatique de f et λ, avec une alerte lorsque les unités saisies sont incompatibles." },
    ],
  ),
  pcLesson(
    "2bac-pc-light",
    "Propagation d'une onde lumineuse",
    "Lumière",
    "Diffraction, indice, réfraction et dispersion",
    "La lumière est une onde électromagnétique. Elle peut se propager dans le vide, et sa vitesse dans un milieu transparent dépend des propriétés de ce milieu.",
    [
      { type: "definition", title: "Onde lumineuse", text: "Une onde lumineuse est une onde électromagnétique pouvant se propager sans milieu matériel." },
      { type: "formula", latex: "c=3,00\\times10^8\\,m\\cdot s^{-1}\\qquad ;\\qquad n=\\frac{c}{v}" },
      { type: "formula", latex: "n_1\\sin i_1=n_2\\sin i_2" },
      { type: "concept", title: "Diffraction", text: "Lorsque l'ouverture devient du même ordre de grandeur que la longueur d'onde, la lumière s'étale après l'ouverture. Plus l'ouverture diminue, plus la diffraction devient visible." },
      { type: "concept", title: "Dispersion", text: "Dans un milieu dispersif, l'indice dépend de la longueur d'onde. La lumière blanche peut donc être séparée en différentes radiations." },
      { type: "example", title: "Exemple guidé", text: "Dans un matériau d'indice n=1,50, la vitesse de propagation de la lumière vaut v=c/n≈2,0×10⁸ m·s⁻¹." },
      { type: "method", title: "Méthode Bac", text: "Pour une réfraction : dessiner la normale, repérer i1 et i2, écrire Snell-Descartes puis vérifier le sens de déviation. Pour un indice : utiliser n=c/v." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Confondre la fréquence, qui reste liée à la source lors d'un changement de milieu, avec la longueur d'onde, qui peut changer." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Sur un schéma de réfraction, les angles se mesurent par rapport à la normale, jamais par rapport à la surface." },
      { type: "highlight", title: "Quick check", text: "Un indice supérieur à 1 correspond à une vitesse inférieure à c dans le modèle usuel des milieux transparents." },
      { type: "exercise", title: "Variante A", text: "Un faisceau passe de l'air vers un milieu d'indice 1,40 avec i1=30°. Calculer i2." },
      { type: "exercise", title: "Variante B", text: "Une fente de 0,20 mm reçoit une lumière de longueur d'onde 600 nm. Décrire qualitativement l'effet attendu si la fente est réduite de moitié." },
      { type: "diagram", title: "Visuel Menti", text: "Schéma de réfraction avec deux milieux, normale, angles i1/i2 et rayon incident/réfracté ; second panneau montrant la diffraction par une fente." },
      { type: "animation", title: "Animation", text: "Un rayon traverse une interface puis change de direction ; la vitesse et la longueur d'onde affichées changent avec le milieu." },
    ],
  ),
  pcLesson(
    "2bac-pc-radioactivity",
    "Décroissance radioactive",
    "Radioactivité",
    "Loi de décroissance, activité et demi-vie",
    "Un noyau radioactif ne permet pas de prévoir l'instant exact de sa désintégration. Sur un grand ensemble de noyaux, l'évolution suit cependant une loi statistique très régulière.",
    [
      { type: "definition", title: "Radioactivité", text: "La radioactivité est la transformation spontanée et aléatoire de noyaux instables." },
      { type: "formula", latex: "N(t)=N_0e^{-\\lambda t}" },
      { type: "formula", latex: "a=\\lambda N\\qquad ;\\qquad T_{1/2}=\\frac{\\ln2}{\\lambda}" },
      { type: "concept", title: "Lire une demi-vie", text: "Après une demi-vie, la moitié des noyaux initiaux reste. Après deux demi-vies, il reste un quart, puis un huitième après trois." },
      { type: "example", title: "Exemple guidé", text: "Pour λ=2,0×10⁻³ s⁻¹, T1/2=0,693/0,0020≈347 s." },
      { type: "method", title: "Méthode Bac", text: "1. Choisir la grandeur recherchée. 2. Vérifier l'unité de temps de λ et t. 3. Utiliser la loi exponentielle ou le nombre de demi-vies. 4. Pour l'activité, utiliser a=λN." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Penser qu'après une demi-vie il ne reste plus aucun noyau. Il en reste 50 % du nombre initial." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Si le graphe est en échelle logarithmique, cherche une droite : elle permet souvent d'identifier λ par la pente." },
      { type: "highlight", title: "Quick check", text: "Trois demi-vies correspondent à une fraction restante de 1/8, soit 12,5 %." },
      { type: "exercise", title: "Variante A", text: "Un échantillon possède T1/2=6,0 h. Quelle fraction reste-t-il après 18 h ?" },
      { type: "exercise", title: "Variante B", text: "Retrouver λ lorsqu'une activité passe de a0 à a0/4." },
      { type: "diagram", title: "Visuel Menti", text: "Frise 0, T1/2, 2T1/2, 3T1/2 avec fractions 100 %, 50 %, 25 %, 12,5 %." },
      { type: "interactive", title: "Interactif", text: "Curseur t : affichage simultané de N/N0 et a/a0." },
    ],
  ),
  pcLesson(
    "2bac-pc-mass-energy",
    "Noyaux, masse et énergie",
    "Énergie nucléaire",
    "Défaut de masse, énergie de liaison, fusion et fission",
    "À l'échelle nucléaire, une très petite variation de masse peut correspondre à une énergie importante. C'est le sens physique de E=mc².",
    [
      { type: "definition", title: "Défaut de masse", text: "Le défaut de masse mesure la différence entre la masse des nucléons séparés et celle du noyau assemblé." },
      { type: "formula", latex: "E=mc^2\\qquad ;\\qquad E_l=\\Delta m\\,c^2" },
      { type: "formula", latex: "\\varepsilon=\\frac{E_l}{A}" },
      { type: "concept", title: "Stabilité", text: "Pour comparer la stabilité de noyaux dans le cadre du programme, on utilise l'énergie de liaison par nucléon. Une valeur plus grande traduit un noyau plus fortement lié." },
      { type: "example", title: "Exemple guidé", text: "Une perte de masse de 0,0020 u correspond à environ 1,86 MeV d'énergie via 1 u≈931,5 MeV/c²." },
      { type: "method", title: "Méthode Bac", text: "Identifier la masse manquante, choisir une unité pratique, calculer l'énergie puis interpréter. Dans un bilan nucléaire, comparer masse initiale et finale avant de conclure sur le signe de l'énergie." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Mélanger défaut de masse et variation de masse de la réaction. Le premier décrit la liaison du noyau ; le second compare l'état initial et l'état final de la réaction." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Note immédiatement la conversion utilisée avant de commencer le calcul pour éviter un facteur 10⁶ ou 10³ perdu en route." },
      { type: "highlight", title: "Quick check", text: "1 MeV≈1,60×10⁻¹³ J." },
      { type: "exercise", title: "Variante A", text: "Modifier légèrement la masse du noyau fourni et recalculer le défaut de masse puis l'énergie de liaison." },
      { type: "exercise", title: "Variante B", text: "Comparer deux noyaux possédant des valeurs de ε légèrement différentes et conclure sur leur stabilité relative." },
      { type: "diagram", title: "Visuel Menti", text: "Nucléons séparés → noyau lié → défaut de masse converti en énergie de liaison." },
    ],
  ),
  pcLesson(
    "2bac-pc-rc",
    "Dipôle RC",
    "Circuit RC",
    "Charge, décharge et constante de temps",
    "Un condensateur ne change pas instantanément de tension. Dans un circuit RC, sa tension évolue progressivement suivant une loi exponentielle.",
    [
      { type: "definition", title: "Condensateur", text: "Un condensateur est un dipôle capable d'accumuler de l'énergie électrique." },
      { type: "formula", latex: "q=CU_C\\qquad ;\\qquad i=C\\frac{dU_C}{dt}\\qquad ;\\qquad \\tau=RC" },
      { type: "formula", latex: "U_C(t)=E\\left(1-e^{-t/\\tau}\\right)" },
      { type: "formula", latex: "U_C(t)=Ee^{-t/\\tau}\\quad\\text{(décharge)}" },
      { type: "concept", title: "Le repère 63 % / 37 %", text: "À t=τ, une charge atteint environ 63 % de sa valeur finale. En décharge, il reste environ 37 % de la valeur initiale." },
      { type: "example", title: "Exemple guidé", text: "Avec R=22 kΩ et C=47 µF, τ=RC≈1,03 s. Vers 5τ, la charge est pratiquement terminée." },
      { type: "method", title: "Méthode Bac", text: "1. Identifier charge ou décharge. 2. Calculer τ=RC. 3. Écrire l'expression correspondante. 4. Vérifier la valeur à t=0. 5. Exploiter t=τ ou 5τ lorsque c'est utile." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Écrire τ=R/C. La constante de temps d'un RC vaut bien τ=RC." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Le bon réflexe est de vérifier la condition initiale avant même de regarder les nombres." },
      { type: "highlight", title: "Quick check", text: "Si R est multipliée par 2 et C reste constant, τ est multipliée par 2 : le circuit devient plus lent." },
      { type: "exercise", title: "Variante A", text: "R=18 kΩ et C=56 µF. Calculer τ puis Uc à t=τ pour une source E=9,0 V." },
      { type: "exercise", title: "Variante B", text: "À partir d'une courbe de charge, lire τ puis déduire C si R est connu." },
      { type: "diagram", title: "Visuel Menti", text: "Circuit RC minimal avec source, résistance, condensateur et interrupteur, puis courbe Uc(t) superposée." },
      { type: "interactive", title: "Interactif", text: "Curseurs R, C et E avec affichage de τ, Uc(t) et du niveau atteint à t=τ." },
    ],
  ),
  pcLesson(
    "2bac-pc-rl",
    "Dipôle RL",
    "Circuit RL",
    "Établissement et interruption du courant",
    "Une bobine s'oppose aux variations rapides du courant. Son inductance impose donc un régime transitoire dans un circuit RL.",
    [
      { type: "definition", title: "Bobine", text: "Une bobine est caractérisée par son inductance L et stocke de l'énergie magnétique lorsqu'elle est parcourue par un courant." },
      { type: "formula", latex: "u_L=ri+L\\frac{di}{dt}\\qquad ;\\qquad E_m=\\frac12Li^2" },
      { type: "formula", latex: "\\tau=\\frac{L}{R+r}\\qquad ;\\qquad I_\\infty=\\frac{E}{R+r}" },
      { type: "concept", title: "Ce qui change", text: "Augmenter L ralentit l'établissement du courant. Augmenter la résistance totale réduit la constante de temps et la valeur finale du courant." },
      { type: "example", title: "Exemple guidé", text: "Avec E=12 V, R=10 Ω, r=2 Ω et L=0,24 H : τ=0,020 s et I∞=1,0 A." },
      { type: "method", title: "Méthode Bac", text: "Identifier la résistance totale, calculer τ, puis utiliser la loi d'établissement ou d'interruption selon la position de l'interrupteur." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Oublier la résistance interne r de la bobine lorsque l'énoncé la fournit." },
      { type: "exam-tip", title: "Réflexe Bac", text: "À t=0, le courant dans une bobine idéale ne saute pas brutalement : vérifie la condition initiale avant de choisir la courbe." },
      { type: "exercise", title: "Variante A", text: "Changer L de 0,24 H à 0,18 H et comparer qualitativement la rapidité de l'établissement." },
      { type: "exercise", title: "Variante B", text: "À partir d'un relevé i(t), déterminer I∞ et τ puis retrouver L." },
      { type: "diagram", title: "Visuel Menti", text: "Circuit RL annoté avec résistance externe, bobine, résistance interne et courbe i(t)." },
      { type: "animation", title: "Animation", text: "Le courant monte progressivement tandis que la pente diminue jusqu'au régime permanent." },
    ],
  ),
  pcLesson(
    "2bac-pc-rlc",
    "Oscillations électriques LC et RLC",
    "Oscillations électriques",
    "Pulsation propre, énergie et amortissement",
    "Un condensateur chargé et une bobine peuvent échanger de l'énergie : l'énergie électrique devient énergie magnétique, puis l'inverse.",
    [
      { type: "formula", latex: "\\omega_0=\\frac1{\\sqrt{LC}}\\qquad ;\\qquad T_0=2\\pi\\sqrt{LC}" },
      { type: "formula", latex: "E_T=\\frac12CU_C^2+\\frac12Li^2" },
      { type: "concept", title: "Échange d'énergie", text: "Quand le condensateur est fortement chargé, son énergie électrique est importante. Plus tard, cette énergie se retrouve dans la bobine sous forme magnétique. Dans un LC idéal, la somme reste constante." },
      { type: "concept", title: "RLC réel", text: "La résistance dissipe de l'énergie : les oscillations s'amortissent et leur amplitude diminue avec le temps." },
      { type: "example", title: "Exemple guidé", text: "Pour L=50 mH et C=20 µF, T0=2π√(LC)≈6,28 ms." },
      { type: "method", title: "Méthode Bac", text: "Calculer T0 ou ω0 avec les unités SI, identifier le caractère idéal ou amorti du circuit, puis relier l'évolution de la courbe à la dissipation d'énergie." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Oublier le 2π dans T0=2π√(LC), ou confondre T0 et ω0." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Sur un graphe oscillant, mesure la distance entre deux maxima successifs plutôt qu'une seule demi-oscillation." },
      { type: "highlight", title: "Quick check", text: "Si C augmente alors que L reste constant, T0 augmente." },
      { type: "exercise", title: "Variante A", text: "Remplacer C par une valeur 20 % plus élevée et prédire l'évolution de T0 avant de calculer." },
      { type: "exercise", title: "Variante B", text: "Comparer une courbe LC idéale et une courbe RLC amortie puis justifier la présence de R." },
      { type: "diagram", title: "Visuel Menti", text: "Deux jauges d'énergie alternent : Ec électrique du condensateur puis Em magnétique de la bobine." },
      { type: "animation", title: "Animation", text: "L'énergie passe graphiquement de C vers L puis revient, tandis qu'un second mode ajoute un amortissement progressif." },
    ],
  ),
  pcLesson(
    "2bac-pc-modulation",
    "Résonance et transmission d'information",
    "Oscillations forcées et transmission",
    "Résonance RLC et modulation d'amplitude",
    "Un circuit RLC forcé répond particulièrement fortement autour de sa fréquence propre. La modulation, elle, permet de transporter une information sur une porteuse.",
    [
      { type: "formula", latex: "Q=\\frac{N_0}{\\Delta N}=\\frac{\\omega_0}{\\Delta\\omega}" },
      { type: "formula", latex: "m=\\frac{U_{max}-U_{min}}{U_{max}+U_{min}}" },
      { type: "concept", title: "Résonance", text: "À la résonance d'un RLC série, les effets inductif et capacitif se compensent. L'intensité est maximale et le déphasage est nul dans le modèle usuel série." },
      { type: "concept", title: "Bande passante", text: "La bande passante mesure l'intervalle de fréquences dans lequel l'intensité reste au moins égale à Imax/√2." },
      { type: "example", title: "Exemple guidé", text: "Si N0=2,0 kHz et ΔN=160 Hz, alors Q=12,5. Plus Q est grand, plus le circuit est sélectif autour de sa résonance." },
      { type: "method", title: "Méthode Bac", text: "Repérer le maximum sur la courbe, lire N0, déterminer les fréquences limites de la bande puis calculer Q. Pour une modulation, lire Umax et Umin sur l'enveloppe avant de calculer m." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Confondre fréquence de résonance et bande passante. La première repère le centre du pic ; la seconde mesure sa largeur." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Pour une courbe, lis les abscisses de gauche et de droite à la même hauteur Imax/√2 avant de calculer ΔN." },
      { type: "exercise", title: "Variante A", text: "Une courbe présente N0=1,8 kHz et ΔN=120 Hz. Calculer Q et commenter la sélectivité." },
      { type: "exercise", title: "Variante B", text: "Une enveloppe de modulation passe de 1,2 V à 0,4 V. Calculer le taux de modulation." },
      { type: "diagram", title: "Visuel Menti", text: "Pic de résonance avec N1, N0, N2 et niveau Imax/√2 ; panneau séparé avec porteuse, signal modulant et enveloppe." },
      { type: "interactive", title: "Interactif", text: "Curseur R : le pic de résonance s'élargit lorsque R augmente. Un second mode calcule m à partir de Umax et Umin." },
    ],
  ),
  pcLesson(
    "2bac-pc-newton",
    "Lois de Newton et dynamique",
    "Mécanique newtonienne",
    "Bilan des forces, projections et plan incliné",
    "Pour expliquer un mouvement, commence par une question simple : quel système étudie-t-on et quelles forces extérieures agit sur lui ?",
    [
      { type: "definition", title: "Référentiel galiléen", text: "Dans le cadre du programme, on choisit un référentiel dans lequel les lois de Newton peuvent s'appliquer sous leur forme usuelle." },
      { type: "formula", latex: "\\sum\\vec F=m\\vec a" },
      { type: "concept", title: "Les trois lois", text: "Si la résultante est nulle, l'accélération est nulle. La deuxième loi relie résultante et accélération. Les interactions réciproques sont de même intensité et de sens opposés." },
      { type: "concept", title: "Plan incliné sans frottement", text: "En choisissant un axe parallèle au plan, la composante du poids selon cet axe vaut mg sinα, tandis que la réaction normale vaut mg cosα." },
      { type: "formula", latex: "a=g\\sin\\alpha\\qquad ;\\qquad R=mg\\cos\\alpha" },
      { type: "example", title: "Exemple guidé", text: "Pour m=2,0 kg et α=30° sans frottement, a=g sin30°≈4,9 m·s⁻²." },
      { type: "method", title: "Méthode Bac", text: "Système → référentiel → schéma → bilan des forces → deuxième loi → projections sur les axes → résultat avec unité." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Dessiner les forces puis projeter sans avoir défini les axes. Les signes deviennent alors impossibles à contrôler." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Le schéma des forces n'est pas décoratif : il doit permettre de lire le signe de chaque projection." },
      { type: "exercise", title: "Variante A", text: "Passer de α=30° à α=24° et recalculer l'accélération sans frottement." },
      { type: "exercise", title: "Variante B", text: "Ajouter un frottement tangent au plan et établir qualitativement son effet sur a." },
      { type: "diagram", title: "Visuel Menti", text: "Bloc sur plan incliné avec poids, réaction, axes et projections mg sinα / mg cosα." },
      { type: "interactive", title: "Interactif", text: "Curseur α : les composantes du poids et l'accélération se mettent à jour." },
    ],
  ),
  pcLesson(
    "2bac-pc-fall",
    "Chute verticale et mouvement sous pesanteur",
    "Mouvements sous pesanteur",
    "Chute libre, lancer vertical et lancer oblique",
    "Quand la pesanteur est la seule force importante, l'accélération est constante et dirigée vers le bas. Le choix de l'axe fixe alors tous les signes.",
    [
      { type: "formula", latex: "v_y(t)=v_{0y}-gt\\qquad ;\\qquad y(t)=y_0+v_{0y}t-\\frac12gt^2" },
      { type: "formula", latex: "t_H=\\frac{v_0}{g}\\qquad ;\\qquad \\Delta y_H=\\frac{v_0^2}{2g}" },
      { type: "concept", title: "Lancer oblique", text: "On décompose la vitesse initiale : v0x=v0 cosα et v0y=v0 sinα, puis on traite séparément les deux directions." },
      { type: "example", title: "Exemple guidé", text: "Avec v0=15 m·s⁻¹ et α=35°, on calcule d'abord v0x et v0y, puis on écrit x(t) et y(t)." },
      { type: "method", title: "Méthode Bac", text: "1. Définir l'origine et l'axe vertical. 2. Écrire les composantes de l'accélération. 3. Utiliser les conditions initiales. 4. Pour une trajectoire, éliminer t." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Changer de convention de signe au milieu du calcul, par exemple prendre g positif puis négatif sans modifier l'équation." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Écris la convention d'axe en une ligne avant toute équation temporelle." },
      { type: "exercise", title: "Variante A", text: "Un objet est lancé verticalement à 12 m·s⁻¹. Déterminer le temps pour atteindre le sommet avec g=9,8 m·s⁻²." },
      { type: "exercise", title: "Variante B", text: "Même situation, mais le point de départ est situé 1,5 m au-dessus du sol. Déterminer une équation y(t)." },
      { type: "diagram", title: "Visuel Menti", text: "Trajectoire parabolique avec vecteurs v0, v0x, v0y et gravité g." },
      { type: "animation", title: "Animation", text: "Le projectile avance horizontalement pendant que sa composante verticale augmente puis diminue sous l'effet de g." },
    ],
  ),
  pcLesson(
    "2bac-pc-plan",
    "Travail, énergie cinétique et mouvement plan",
    "Travail et énergie",
    "Travail d'une force, énergie cinétique et projectile",
    "Le travail d'une force permet de mesurer son transfert d'énergie mécanique pendant un déplacement. Le théorème de l'énergie cinétique transforme ensuite ce bilan en relation sur la vitesse.",
    [
      { type: "formula", latex: "E_c=\\frac12mv^2\\qquad ;\\qquad \\Delta E_c=\\sum W(\\vec F)" },
      { type: "formula", latex: "W_{AB}(\\vec F)=F\\,AB\\cos\\theta" },
      { type: "concept", title: "Signe du travail", text: "Travail positif : force motrice. Travail nul : force perpendiculaire au déplacement. Travail négatif : force résistante." },
      { type: "example", title: "Exemple guidé", text: "Une force constante de 12 N agit sur 4,0 m dans sa direction. Son travail vaut 48 J. Si elle s'oppose au déplacement, le travail vaut -48 J." },
      { type: "method", title: "Méthode Bac", text: "Lister les forces, calculer séparément leurs travaux, additionner puis poser ΔEc=ΣW. Pour une force de pesanteur, utiliser W(P)=mg(zA−zB)." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Oublier le carré dans Ec=½mv² ou donner un travail en watts au lieu de joules." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Fais une ligne « initial → final » avant de calculer ΔEc. Cela évite d'inverser le signe." },
      { type: "highlight", title: "Quick check", text: "Si une force est perpendiculaire au déplacement, son travail est nul." },
      { type: "exercise", title: "Variante A", text: "Une force de 15 N agit sur 3,5 m avec un angle de 30°. Calculer son travail." },
      { type: "exercise", title: "Variante B", text: "À partir de la vitesse initiale et du travail total, retrouver la vitesse finale." },
      { type: "diagram", title: "Visuel Menti", text: "Bloc en mouvement avec force F, déplacement AB et angle θ, puis jauge d'énergie cinétique avant/après." },
    ],
  ),
  pcLesson(
    "2bac-pc-orbit",
    "Satellites artificiels et planètes",
    "Gravitation",
    "Orbite circulaire et lois de Kepler",
    "Un satellite en orbite n'est pas « sans force » : la gravitation courbe en permanence sa trajectoire et fournit l'accélération centripète.",
    [
      { type: "formula", latex: "v=\\sqrt{\\frac{GM}{R}}\\qquad ;\\qquad T=2\\pi\\sqrt{\\frac{R^3}{GM}}" },
      { type: "concept", title: "Rayon orbital", text: "Pour un satellite situé à l'altitude h au-dessus de la Terre, le rayon orbital est R=RT+h. Ne pas utiliser h seul dans les formules orbitales." },
      { type: "concept", title: "Kepler", text: "Pour les orbites autour d'un même astre, T²/R³ est constant dans le modèle circulaire associé." },
      { type: "example", title: "Exemple guidé", text: "Si deux satellites ont R2=1,20R1, alors T2/T1=(1,20)^(3/2)≈1,31 : le satellite plus éloigné a une période plus longue." },
      { type: "method", title: "Méthode Bac", text: "1. Identifier l'astre central. 2. Écrire la force gravitationnelle. 3. Utiliser le mouvement circulaire uniforme. 4. Égaler l'accélération gravitationnelle à l'accélération centripète." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Prendre le rayon de la Terre au lieu du rayon orbital R=RT+h." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Avant tout calcul, fais un schéma Terre + centre de l'orbite + R. Le rayon est mesuré depuis le centre de l'astre." },
      { type: "highlight", title: "Quick check", text: "À rayon plus grand autour du même astre, la vitesse orbitale diminue et la période augmente." },
      { type: "exercise", title: "Variante A", text: "Comparer deux orbites de rayons 7,0×10⁶ m et 8,0×10⁶ m par le rapport des périodes." },
      { type: "exercise", title: "Variante B", text: "Identifier parmi trois descriptions laquelle peut correspondre à un satellite géostationnaire." },
      { type: "diagram", title: "Visuel Menti", text: "Terre, centre, rayon orbital R, altitude h et vecteur vitesse tangent à l'orbite." },
      { type: "animation", title: "Animation", text: "Deux satellites orbitent à des rayons différents ; la période plus grande du satellite éloigné apparaît visuellement." },
    ],
  ),
  pcLesson(
    "2bac-pc-rotation",
    "Dynamique de rotation et oscillateurs mécaniques",
    "Rotation et oscillations mécaniques",
    "Moment, moment d'inertie, ressort et pendules",
    "Pour une rotation, la force seule ne suffit pas : sa distance à l'axe compte. Pour les oscillations, l'idée centrale est celle d'une force ou d'un moment de rappel.",
    [
      { type: "formula", latex: "\\sum M_\\Delta(\\vec F)=J_\\Delta\\alpha\\qquad ;\\qquad M=Fd" },
      { type: "formula", latex: "T_0=2\\pi\\sqrt{\\frac{m}{K}}" },
      { type: "formula", latex: "T_0=2\\pi\\sqrt{\\frac{J_\\Delta}{C}}" },
      { type: "concept", title: "Moment", text: "Deux forces de même intensité peuvent produire des effets de rotation très différents si leurs bras de levier sont différents." },
      { type: "concept", title: "Ressort", text: "Autour de l'équilibre, la force de rappel du ressort est proportionnelle au déplacement et de sens opposé." },
      { type: "example", title: "Exemple guidé", text: "Avec m=0,20 kg et K=50 N·m⁻¹, la période propre du ressort vaut environ 0,40 s." },
      { type: "method", title: "Méthode Bac", text: "Pour une rotation : choisir l'axe, définir le signe des moments, calculer J puis appliquer la relation dynamique. Pour un oscillateur : identifier la position d'équilibre, la pulsation propre puis la période." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Confondre bras de levier d et distance au point d'application. Le bras de levier est la distance perpendiculaire à la ligne d'action." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Dessine la ligne d'action de la force avant de mesurer le bras de levier." },
      { type: "exercise", title: "Variante A", text: "Déplacer une masse plus loin de l'axe et prévoir qualitativement ce qui arrive à J." },
      { type: "exercise", title: "Variante B", text: "Changer m ou K d'un oscillateur et prévoir le sens de variation de T0." },
      { type: "diagram", title: "Visuel Menti", text: "Bras de levier d sur une barre en rotation, puis ressort-masse autour de sa position d'équilibre." },
      { type: "animation", title: "Animation", text: "La barre tourne autour d'un axe ; dans un second mode le ressort oscille et les positions extrêmes sont repérées." },
    ],
  ),
  pcLesson(
    "2bac-pc-work-energy",
    "Particule chargée dans un champ magnétique et champs",
    "Champs électriques et magnétiques",
    "Force de Lorentz et mouvement circulaire",
    "Un champ magnétique peut courber la trajectoire d'une particule chargée sans modifier sa vitesse lorsque la force magnétique reste perpendiculaire à la vitesse.",
    [
      { type: "formula", latex: "\\vec F=q\\,\\vec v\\times\\vec B" },
      { type: "formula", latex: "r=\\frac{mv}{|q|B}\\qquad ;\\qquad T=\\frac{2\\pi m}{|q|B}" },
      { type: "concept", title: "Travail nul", text: "La force magnétique est perpendiculaire à la vitesse dans le modèle considéré. Elle ne fournit donc pas de travail et l'énergie cinétique reste constante." },
      { type: "example", title: "Exemple guidé", text: "À B constant et |q| identique, augmenter m augmente le rayon r pour une même vitesse." },
      { type: "method", title: "Méthode Bac", text: "Identifier v, B et q, déterminer la direction de la force avec la règle du produit vectoriel, puis égaler l'effet magnétique à l'accélération centripète si le mouvement est circulaire." },
      { type: "common-mistake", title: "Erreur fréquente", text: "Placer la force dans la direction de la vitesse. Elle est perpendiculaire à celle-ci dans le cas étudié." },
      { type: "exam-tip", title: "Réflexe Bac", text: "Fais d'abord le triplet v, B, F sur le schéma avant de choisir le sens de courbure." },
      { type: "exercise", title: "Variante A", text: "Doubler B et prédire l'évolution de r et T avant le calcul." },
      { type: "exercise", title: "Variante B", text: "Comparer deux isotopes de masses différentes injectés avec la même énergie cinétique." },
      { type: "diagram", title: "Visuel Menti", text: "Particule entrant dans une zone de champ B, vecteur vitesse tangent, force perpendiculaire et trajectoire circulaire." },
      { type: "interactive", title: "Interactif", text: "Curseurs m, |q|, v et B avec affichage automatique de r et T." },
    ],
  ),
];

export const pcLessonsDetailed = secondBacPcLessonsDetailed;
