insert into public.mission_helios_chapters (day, chapter_number, title, mission_context) values
(1,1,'Limites et continuité','ORION reçoit un flux de données radar bruitées sur l''objet HL-2044. Avant tout calcul de trajectoire, l''équipe doit s''assurer que les fonctions de mesure sont bien définies, ne sautent pas, et ont un comportement prévisible aux bornes du domaine d''observation.'),
(2,2,'Dérivation, étude de fonctions','Modéliser la vitesse angulaire.'),
(3,3,'Accroissements finis','Borner les erreurs de mesure.'),
(4,4,'Suites numériques','Itérer le modèle orbital.'),
(5,5,'Fonctions logarithmiques','Travailler sur les échelles de magnitude.'),
(6,6,'Fonction exponentielle','Modéliser la décroissance du signal radar.'),
(7,7,'Primitives','Remonter à la position depuis la vitesse.'),
(8,8,'Calcul intégral','Calculer énergie et aires sous la courbe.'),
(9,9,'Équations différentielles','Construire le modèle dynamique complet.'),
(10,10,'Nombres complexes','Traiter le signal et les rotations.'),
(11,11,'Géométrie dans l''espace','Repérer en 3D la trajectoire.'),
(12,12,'Dénombrement et probabilités','Évaluer la fiabilité des capteurs.'),
(13,13,'Arithmétique dans Z','Sécuriser les communications par arithmétique et cryptographie.'),
(14,14,'Structures algébriques','Vérifier formellement le modèle.'),
(15,15,'Espaces vectoriels','Réaliser la synthèse finale et la décision de tir.');

insert into public.mission_helios_exercises (chapter_id,exercise_number,title,context,parts,animation,difficulty,is_synthesis)
select c.id,v.exercise_number,v.title,v.context,v.parts::jsonb,v.animation,v.difficulty,v.is_synthesis
from public.mission_helios_chapters c
join (values
(1,'Premier signal','Le signal brut est modélisé par f(x) = (2x²-3x-2)/(x-2) sur les premières secondes d''acquisition.','["Déterminer le domaine de définition de f.","Calculer lim(x→2) f(x) en factorisant le numérateur.","En déduire si f est prolongeable par continuité en 2, et donner ce prolongement."]','Courbe de f qui se trace, un point creux clignote en x=2 puis se remplit.',1,false),
(2,'Dérive à l''infini','ORION extrapole le signal pour t très grand.','["Calculer lim(x→+∞) (3x²-5x+1)/(x²+2).","Même question pour (3x²-5x+1)/(x³+2), en factorisant par le terme dominant.","Comparer les deux résultats et expliquer la différence de comportement."]','Deux courbes se tracent côte à côte, une asymptote horizontale s’allume.',1,false),
(3,'Bruit de fond','Une composante du signal est h(x) = sin(x)/x, utilisée pour filtrer le bruit.','["Justifier que lim(x→0) sin(x)/x = 1 (admis, à utiliser).","En déduire lim(x→0) sin(3x)/x par changement de variable u = 3x.","En déduire lim(x→0) (1-cos(x))/x² à l’aide de l’identité 1-cos(x) = 2sin²(x/2)."]','Oscillogramme qui se stabilise autour d’une valeur, curseur qui zoome sur 0.',1,false),
(4,'Forme indéterminée classique','Calcul de la vitesse instantanée d’approche.','["Montrer que (√(x+1)-1)/x est une forme 0/0 en x=0.","Lever l’indétermination en multipliant par la quantité conjuguée.","Calculer la limite en x=0."]','Expression qui se réécrit à l’écran ligne par ligne, quantité conjuguée en surbrillance.',1,false),
(5,'Comparaison de croissances','Deux capteurs renvoient des amplitudes en x² et en ln(x).','["Rappeler (sans démonstration) le résultat de croissances comparées entre x² et ln(x) en +∞.","Calculer lim(x→+∞) (x² - ln(x)).","Calculer lim(x→+∞) ln(x)/x²."]','Deux courbes divergent, l’une s’envole, l’autre reste plate à l’écran.',2,false),
(6,'Encadrement','Le signal est perturbé par un terme oscillant borné.','["Justifier que -1 ≤ sin(x) ≤ 1.","En déduire un encadrement de f(x) = 2 + sin(x)/x pour x>0.","Utiliser le théorème des gendarmes pour conclure sur lim(x→+∞) f(x)."]','Deux courbes gendarmes encadrent la courbe du signal qui se resserre vers 2.',2,false),
(7,'Continuité par morceaux','Le protocole d’acquisition change de formule selon la phase du vol.','["Une fonction g est définie par g(x)=x²+1 si x<1 et g(x)=3x-1 si x≥1 : étudier la continuité en 1.","Modifier la constante 3x-1 en 3x+c pour que g soit continue en 1 ; déterminer c.","Conclure sur la continuité de g sur R avec cette valeur de c."]','Deux morceaux de courbe qui se rejoignent ou non en un point, jauge raccord OK/KO.',2,false),
(8,'Théorème des valeurs intermédiaires','Il faut prouver qu’à un instant donné, l’altitude mesurée s’annule.','["Justifier que h(x)=x³-3x+1 est continue sur [0;2].","Calculer h(0) et h(2), puis déduire l’existence d’une solution à h(x)=0 sur cet intervalle.","Encadrer cette solution à 10⁻¹ près par balayage ou dichotomie manuelle."]','Segment [0;2] qui se subdivise, zone colorée qui se resserre autour de la solution.',3,false),
(9,'Unicité de solution','ORION doit garantir qu’il n’existe qu’un seul instant de passage.','["Étudier les variations de h(x)=x³-3x+1 sur [0;2] à l’aide du signe de h′.","En déduire que h est strictement monotone sur un sous-intervalle pertinent.","Conclure, via le corollaire du TVI, à l’unicité de la solution sur cet intervalle."]','Courbe strictement monotone mise en évidence, un seul point d’intersection clignote.',3,false),
(10,'Limite et suite couplées','Un capteur redémarre à intervalles réguliers, modélisé par une suite liée à une fonction.','["On pose u(n) = f(1/n) avec f(x)=(1-cos x)/x² pour x≠0. Exprimer u(n).","Utiliser le résultat de l’exercice 3 pour deviner lim(n→+∞) u(n).","Justifier proprement ce résultat par composition de limites."]','Suite de points qui se rapprochent d’une valeur limite sur l’axe vertical.',3,false),
(11,'Asymptote oblique','La trajectoire d’approche lointaine est modélisée par r(x) = (x²+1)/x.','["Écrire r(x) sous la forme ax+b+c/x.","Calculer lim(x→+∞) (r(x)-(ax+b)) pour justifier l’asymptote oblique y=ax+b.","Étudier la position de la courbe par rapport à cette asymptote à l’aide du signe de c/x."]','Droite oblique qui apparaît en pointillés, la courbe s’en rapproche progressivement.',3,false),
(12,'Limite à gauche / à droite','Un capteur affiche une discontinuité suspecte à surveiller.','["Étudier lim(x→1⁻) et lim(x→1⁺) de f(x)=|x-1|/(x-1).","Conclure sur l’existence d’une limite en 1.","Proposer une valeur de f(1) qui rendrait f continue à droite, mais pas continue en 1."]','Deux flèches venant de gauche et de droite s’arrêtent à des hauteurs différentes.',3,false),
(13,'Composition de limites','Le signal traité passe par un second filtre exponentiel-log.','["Calculer lim(x→0) ln(1+x)/x (résultat de cours à réutiliser, admis si besoin).","En déduire lim(x→0) ln(1+3x²)/x² par changement de variable u=3x².","Généraliser : donner lim(x→0) ln(1+ax²)/x² en fonction de a."]','Bloc filtre 1 puis filtre 2 qui s’allument successivement à l’écran.',4,false),
(14,'Croissances comparées avec exponentielle','Un modèle de décroissance rapide du signal est envisagé.','["Rappeler lim(x→+∞) x²e^{-x}.","Calculer lim(x→+∞) (x²+3x)e^{-x} en factorisant.","Interpréter physiquement ce résultat pour la mission : le signal s’éteint-il vite ?"]','Courbe qui plonge rapidement vers 0, compteur d’intensité qui décroît.',4,false),
(15,'Fonction non continue mais bornée','Vérifier qu’un capteur défectueux reste malgré tout dans une plage physique.','["Étudier la fonction partie entière E(x) sur [0;3] : où est-elle discontinue ?","Montrer que E est néanmoins bornée sur cet intervalle.","Discuter : peut-on appliquer le TVI à E sur [0;3] ? Justifier pourquoi ou pourquoi pas."]','Courbe en escalier qui se dessine marche par marche.',4,false),
(16,'Limite d’une fonction composée avec paramètre','Calibration d’un paramètre k du modèle.','["Soit f_k(x)=(x²-k²)/(x-k) pour x≠k. Simplifier f_k(x).","Calculer lim(x→k) f_k(x).","Pour quelle valeur de k la limite trouvée vaut-elle 10 ?"]','Curseur k qu’on fait glisser, la limite affichée se met à jour en direct.',4,false),
(17,'Étude complète de continuité sur un intervalle','Validation finale du signal avant transmission au chapitre suivant.','["Soit f(x)=(x²-1)/(x-1) si x≠1 et f(1)=2. Étudier la continuité de f en 1.","Modifier f(1) pour rendre f continue en 1 ; comparer avec la valeur initiale 2.","Tracer ou décrire l’allure du graphe dans les deux cas, avec et sans le bon prolongement."]','Bascule entre deux versions du graphe, point manquant puis point comblé.',4,false),
(18,'Théorème des valeurs intermédiaires appliqué à un cas concret','Il faut garantir qu’un seuil critique de vitesse est bien atteint une fois.','["Soit v(t)=t³-2t+3 sur [0;2]. Vérifier que v est continue.","Montrer que l’équation v(t)=4 admet au moins une solution sur [0;2].","Encadrer cette solution à 0,5 près."]','Jauge de vitesse qui grimpe, seuil 4 matérialisé par une ligne de référence franchie.',4,false),
(19,'Piège classique : limite qui n’existe pas','Un signal oscillant rapide met en doute la fiabilité d’un capteur.','["Étudier lim(x→+∞) sin(x) : existe-t-elle ? Justifier par les suites x_n=2nπ et x_n=π/2+2nπ.","Que peut-on dire de lim(x→+∞) sin(x)/x ? Justifier avec le théorème des gendarmes.","Conclure sur la fiabilité de ce capteur pour une mesure à long terme."]','Signal qui oscille sans se stabiliser, puis une enveloppe qui tend vers 0.',5,false),
(20,'SYNTHÈSE DU JOUR 1 — Rapport de validation','Dr. Arvez doit signer le rapport de validation des données avant le Jour 2.','["Soit F(x)=(e^x-1)/x pour x≠0 et F(0)=1. Calculer lim(x→0) F(x) en admettant lim(x→0)(e^x-1)/x=1, et conclure sur la continuité de F en 0.","Soit G(x)=x·sin(1/x) pour x≠0. Montrer, par encadrement, que lim(x→0) G(x)=0, et proposer un prolongement continu en 0.","Un capteur mesure P(t)=t³-4t+1 sur [-3;3]. Montrer que P s’annule au moins trois fois sur cet intervalle par étude de signe aux bornes de sous-intervalles bien choisis.","Rédiger la conclusion du rapport : les données du Jour 1 sont-elles exploitables pour la suite de la mission, Jour 2 : dérivation ?"]','Tableau de bord qui passe au vert, tampon VALIDÉ — Jour 1, transition vers Jour 2.',5,true)
) v(exercise_number,title,context,parts,animation,difficulty,is_synthesis) on true
where c.day=1;