import { FunctionsHttpError } from "@supabase/supabase-js";
import { supabase } from "../../lib/supabase";
import type { Exercise } from "../../types/content";
import type { TrackId } from "../../types/academic";

export type CorrectionVerdict = "correct" | "mostly_correct" | "partially_correct" | "incorrect";
export type AICorrectionResult = { score:number|null; verdict:CorrectionVerdict; summary:string; strengths:string[]; errors:Array<{location:string;expected:string;observed:string;fix:string}>; correctedSolution:string; nextStep:string };
type FunctionResponse={success?:boolean;data?:AICorrectionResult;error?:string;detail?:string};
async function getFunctionError(error:unknown){if(FunctionsHttpError&&error instanceof FunctionsHttpError){try{const payload=(await error.context.json()) as FunctionResponse;if(payload?.detail)return `${payload.error??"Le correcteur IA est indisponible."} ${payload.detail}`;if(payload?.error)return payload.error;}catch{}}if(error instanceof Error&&error.message.trim())return error.message;return "Le correcteur IA est indisponible.";}
export async function correctExerciseWithAI(params:{exercise:Exercise;answers:string[];trackId:TrackId}){const{exercise,answers,trackId}=params;if(!answers.some(a=>a.trim()))throw new Error("Écris au moins une réponse avant de lancer la correction.");try{const{data,error}=await supabase.functions.invoke<FunctionResponse>("ai-corrector",{body:{exercise:{id:exercise.id,title:exercise.title,statement:exercise.statement,type:exercise.type,difficulty:exercise.difficulty,expectedAnswer:exercise.expectedAnswer,correction:exercise.correction,target:exercise.target},answers,trackId}});if(error)throw error;if(!data?.success||!data.data)throw new Error(data?.detail?`${data.error??"Le correcteur IA est indisponible."} ${data.detail}`:data?.error??"Le correcteur IA est indisponible.");const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!userData.user)throw new Error("Utilisateur non authentifié.");const{error:saveError}=await supabase.from("ai_corrections").insert({user_id:userData.user.id,exercise_id:exercise.id,subject_id:exercise.target.subjectId,track_id:trackId,statement:exercise.statement,student_answers:answers,result:data.data,provider:"gemini"});if(saveError)throw saveError;return data.data;}catch(error){throw new Error(await getFunctionError(error));}}
