import "jsr:@supabase/functions-js@2/edge-runtime.d.ts";

const MODEL = "gemini-3.5-flash-lite";
const ALLOWED_MODES = new Set(["handnote", "summary", "flashcards", "quiz"]);
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Content-Type": "application/json", "Cache-Control": "no-store" };
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: corsHeaders }); }

const lessonSchema = { type: "object", properties: {
  title: { type: "string" }, intro: { type: "string" }, prerequisites: { type: "array", items: { type: "string" } }, learningObjectives: { type: "array", items: { type: "string" } },
  sections: { type: "array", items: { type: "object", properties: {
    title: { type: "string" }, explanation: { type: "string" }, intuition: { type: "string" }, keyConcepts: { type: "array", items: { type: "string" } },
    definitions: { type: "array", items: { type: "object", properties: { term: { type: "string" }, definition: { type: "string" } }, required: ["term", "definition"] } },
    formulas: { type: "array", items: { type: "string" } }, derivations: { type: "array", items: { type: "string" } }, examples: { type: "array", items: { type: "string" } },
    checkpoints: { type: "array", items: { type: "object", properties: { question: { type: "string" }, answer: { type: "string" }, why: { type: "string" } }, required: ["question", "answer", "why"] } },
    commonMistakes: { type: "array", items: { type: "string" } }, examFocusPoints: { type: "array", items: { type: "string" } }
  }, required: ["title", "explanation", "intuition", "keyConcepts", "definitions", "formulas", "derivations", "examples", "checkpoints", "commonMistakes", "examFocusPoints"] } },
  mustRemember: { type: "array", items: { type: "string" } },
  selfAssessment: { type: "array", items: { type: "object", properties: { question: { type: "string" }, answer: { type: "string" } }, required: ["question", "answer"] } },
  progressiveExercises: { type: "array", items: { type: "object", properties: { statement: { type: "string" }, hint: { type: "string" }, answer: { type: "string" }, difficulty: { type: "string", enum: ["easy", "medium", "hard"] } }, required: ["statement", "hint", "answer", "difficulty"] } },
  sourceNotes: { type: "array", items: { type: "string" } }, estimatedStudyTimeMinutes: { type: "integer" }
}, required: ["title", "intro", "prerequisites", "learningObjectives", "sections", "mustRemember", "selfAssessment", "progressiveExercises", "sourceNotes", "estimatedStudyTimeMinutes"] };

const schemas: Record<string, Record<string, unknown>> = {
  handnote: lessonSchema,
  summary: { type: "object", properties: { title: { type: "string" }, summary: { type: "string" }, keyPoints: { type: "array", items: { type: "string" } }, formulas: { type: "array", items: { type: "string" } } }, required: ["title", "summary", "keyPoints", "formulas"] },
  flashcards: { type: "object", properties: { title: { type: "string" }, cards: { type: "array", items: { type: "object", properties: { question: { type: "string" }, answer: { type: "string" }, difficulty: { type: "string", enum: ["easy", "medium", "hard"] } }, required: ["question", "answer", "difficulty"] } } }, required: ["title", "cards"] },
  quiz: { type: "object", properties: { title: { type: "string" }, questions: { type: "array", items: { type: "object", properties: { question: { type: "string" }, choices: { type: "array", items: { type: "string" }, minItems: 4, maxItems: 4 }, answerIndex: { type: "integer" }, explanation: { type: "string" }, conceptIds: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 4 }, topic: { type: "string" }, difficulty: { type: "string", enum: ["easy", "medium", "hard"] } }, required: ["question", "choices", "answerIndex", "explanation", "conceptIds", "topic", "difficulty"] } } }, required: ["title", "questions"] }
};

function promptFor(mode: string, text: string, subject?: string, chapter?: string, track?: string) {
  const context = [subject ? `Matière: ${subject}` : "", chapter ? `Chapitre: ${chapter}` : "", track ? `Parcours: ${track}` : ""].filter(Boolean).join("\n");
  if (mode === "handnote") return `Tu es le moteur pédagogique de MentionMax pour le bac marocain. Tu ne fais PAS un résumé court. Tu reconstruis une vraie leçon longue à partir d'une vidéo éducative.\n\n${context}\n\nOBJECTIF: créer une leçon que l'élève peut étudier à la place de regarder la vidéo. Elle doit être plus claire, mieux structurée et pédagogiquement plus utile que la vidéo, tout en restant fidèle.\n\nSTYLE MENTIMAX: longue et complète; style de notes manuscrites de cours; sections nettes, explications, formules isolées, encadrés conceptuels, exemples, pièges, annotations et rappels. Préserve les intuitions et analogies utiles; supprime répétitions et digressions; répare les sauts logiques. Pour maths/physique/chimie, écris TOUTE notation mathématique en LaTeX avec délimiteurs \\( ... \\) pour l'interne et \\[ ... \\] pour les équations isolées. N'écris jamais une formule mathématique brute hors délimiteurs. Pour SMB, n'introduis jamais de SVT. Ne présente pas une addition de l'IA comme venant de la vidéo.\n\nSTRUCTURE: introduction; prérequis; objectifs; 6 à 12 sections substantielles selon la densité; chaque section avec explication, intuition si utile, définitions, formules/relations, exemples, erreurs fréquentes; checkpoints actifs; synthèse; éléments à mémoriser; 5 à 10 questions d'auto-évaluation; 3 à 6 exercices progressifs si possible. Conserve les raisonnements importants et les conditions de validité. Ne remplis pas avec du blabla.\n\nRéponds uniquement avec les champs du schéma imposé. Le texte des champs peut être long. Ne mets ni Markdown autour de la réponse, ni préambule.\n\nTexte source de la vidéo:\n${text}`;
  if (mode === "quiz") return `Tu es le moteur de quiz pédagogique de MentionMax pour le bac marocain.\n${context}\n\nCrée un quiz QCM fidèle au contenu source. Chaque question doit tester une notion identifiable, pas un détail artificiel.\n\nPour chaque question retourne aussi: conceptIds (1 à 4 identifiants courts et stables, par exemple "derivee", "tableau-variations"), topic (intitulé lisible de la notion), difficulty (easy, medium ou hard). Ces métadonnées servent uniquement au suivi pédagogique et ne doivent pas être affichées comme texte de question.\n\nLes choix doivent être plausibles et une seule réponse doit être correcte. Les explications doivent aider l'élève à comprendre son erreur.\n\nRéponds uniquement avec les champs du schéma imposé, sans Markdown ni préambule.\n\nTexte source:\n${text}`;
  return `Tu es le moteur pédagogique de MentionMax pour le bac marocain.\n${context}\n\nTransforme le texte source en ${mode}. Sois fidèle, clair et directement utile à l'étude. N'invente rien. Toute notation mathématique doit utiliser \\( ... \\) ou \\[ ... \\]. Pour SMB, n'introduis jamais de SVT.\n\nRéponds uniquement avec les champs du schéma imposé, sans Markdown ni préambule.\n\nTexte source:\n${text}`;
}

function extractText(payload: any): string { const chunks: string[] = []; if (typeof payload?.output_text === "string") chunks.push(payload.output_text); if (Array.isArray(payload?.steps)) for (const step of payload.steps) { if (typeof step?.text === "string") chunks.push(step.text); if (Array.isArray(step?.content)) for (const part of step.content) if (typeof part?.text === "string") chunks.push(part.text); if (Array.isArray(step?.output)) for (const part of step.output) if (typeof part?.text === "string") chunks.push(part.text); } if (Array.isArray(payload?.outputs)) for (const item of payload.outputs) { if (typeof item?.text === "string") chunks.push(item.text); if (Array.isArray(item?.content)) for (const part of item.content) if (typeof part?.text === "string") chunks.push(part.text); } if (typeof payload?.text === "string") chunks.push(payload.text); return chunks.join("\n").trim(); }
Deno.serve(async (req) => { if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders }); if (req.method !== "POST") return json({ success: false, error: "Méthode non autorisée." }, 405); try { const apiKey = Deno.env.get("ai-studio-generate"); if (!apiKey) return json({ success: false, error: "Le secret ai-studio-generate est manquant dans Supabase." }, 500); const body = await req.json(); const mode = typeof body?.mode === "string" ? body.mode : ""; const text = typeof body?.text === "string" ? body.text.trim() : ""; const subject = typeof body?.subject === "string" ? body.subject.trim() : undefined; const chapter = typeof body?.chapter === "string" ? body.chapter.trim() : undefined; const track = typeof body?.track === "string" ? body.track.trim() : undefined; if (!ALLOWED_MODES.has(mode)) return json({ success: false, error: "Mode de génération invalide." }, 400); if (!text) return json({ success: false, error: "Le texte source est vide." }, 400); if (text.length > 120000) return json({ success: false, error: "Le texte source est trop long. Réduis ou découpe le contenu." }, 413); const response = await fetch("https://generativelanguage.googleapis.com/v1beta/interactions", { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey, "Api-Revision": "2026-05-20" }, body: JSON.stringify({ model: MODEL, input: [{ type: "text", text: promptFor(mode, text, subject, chapter, track) }], store: false, response_format: { type: "text", mime_type: "application/json", schema: schemas[mode] }, generation_config: { max_output_tokens: mode === "handnote" ? 20000 : mode === "quiz" || mode === "flashcards" ? 4500 : 3000, thinking_level: mode === "handnote" ? "low" : "minimal" } }), signal: AbortSignal.timeout(150000) }); const payload = await response.json().catch(() => null); if (!response.ok) return json({ success: false, error: "La génération IA a échoué.", detail: payload?.error?.message ?? `Gemini HTTP ${response.status}` }, response.status); const rawText = extractText(payload); if (!rawText) return json({ success: false, error: "Le modèle n'a renvoyé aucun contenu." }, 502); try { return json({ success: true, mode, result: JSON.parse(rawText), model: MODEL }); } catch (error) { return json({ success: false, error: error instanceof Error ? error.message : "Réponse IA invalide.", raw: rawText.slice(0, 4000) }, 502); } } catch (error) { return json({ success: false, error: error instanceof Error ? error.message : "Erreur inattendue." }, 500); } });